'use client'
import Navbar from '@/components/Navbar'
// import ThemeProviders from './ThemeProviders'
import './globals.css'
import TopHeader from '@/components/TopHeader'
import Footer from '@/components/Footer'
import Lottie from "lottie-react";
import scrollBtn from "../assets/animation_llunknd0.json";
import ScrollToTop from "react-scroll-to-top";

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <TopHeader></TopHeader>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
          <ScrollToTop smooth component={<Lottie className='bg-cyan-500 rounded w-14 h-14' animationData={scrollBtn} loop={true} />}></ScrollToTop>
      </body>
    </html>
  )
}
